In [3]:
import numpy as np 
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [4]:
ar = np.arange(0,10,1)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
ar = np.arange(10,-1,-1)
ar

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [9]:
ar = np.arange(2,20,2)
ar

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
ln = np.linspace(0,100,18)
ln

array([  0.        ,   5.88235294,  11.76470588,  17.64705882,
        23.52941176,  29.41176471,  35.29411765,  41.17647059,
        47.05882353,  52.94117647,  58.82352941,  64.70588235,
        70.58823529,  76.47058824,  82.35294118,  88.23529412,
        94.11764706, 100.        ])

In [14]:
i = np.eye(5)
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
print(ar.size)

9
